Add missing headers to fix compilation
I ran into a few errors when trying to compile harb on Ubuntu 22.04
(gcc 11.4.0):

```
main.cc:35:3: error: ‘va_start’ was not declared in this scope
   35 |   va_start(args, fmt);
      |   ^~~~~~~~

ruby_heap_obj.h:132:25: error: ‘FILE’ has not been declared
  132 |   void print_ref_object(FILE *);
      |                         ^~~~

ruby_heap_obj.h:64:21: error: ‘uint64_t’ was not declared in this scope
   64 | typedef std::vector<uint64_t> RubyHeapAddrList;
      |                     ^~~~~~~~
```

Adding these headers fixes compilation.